POST http://localhost:3300/auth/register
Content-Type: application/json

{
    "name":"sabrina",
    "email":"sabrina1@mail.com",
    "password":"password123"
}

### 
POST http://localhost:3300/auth/login
Content-Type: application/json

{
    "email":"sabrina@mail.com",
    "password":"password123"
}

###
GET http://localhost:3300/auth/whoami
Authorization: : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6InNhYnJpbmEiLCJlbWFpbCI6InNhYnJpbmFAbWFpbC5jb20iLCJpYXQiOjE2ODQ0ODcyMjB9.brnInFinLFdnerzxetMGWyxR7icXwCMnoGemiDCwyOM